"""Add feedback fields to dawah_requests

Revision ID: 08a9018b1b02
Revises: 002
Create Date: 2026-03-12 00:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a9018b1b02'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dawah_requests', sa.Column('submitter_feedback', sa.Text(), nullable=True))
    op.add_column('dawah_requests', sa.Column('preacher_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dawah_requests', 'preacher_feedback')
    op.drop_column('dawah_requests', 'submitter_feedback')
    # ### end Alembic commands ###
