"""add religion table and religion_id to interested_persons

Revision ID: 5c4652d62c25
Revises: a1b2c3d4e5f6
Create Date: 2026-03-25 23:22:20.069858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c4652d62c25'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('religions',
        sa.Column('religion_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('religion_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('religion_id')
    )
    op.add_column('dawah_requests', sa.Column('invited_religion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dawah_requests', 'religions', ['invited_religion_id'], ['religion_id'])
    op.add_column('interested_persons', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.add_column('interested_persons', sa.Column('religion', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'interested_persons', 'religions', ['religion_id'], ['religion_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interested_persons', type_='foreignkey')
    op.drop_column('interested_persons', 'religion')
    op.drop_column('interested_persons', 'religion_id')
    op.drop_constraint(None, 'dawah_requests', type_='foreignkey')
    op.drop_column('dawah_requests', 'invited_religion_id')
    op.drop_table('religions')
    # ### end Alembic commands ###
