"""add religion table and religion_id to interested_persons

Revision ID: 5c4652d62c25
Revises: a1b2c3d4e5f6
Create Date: 2026-03-25 23:22:20.069858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c4652d62c25'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dashboard_snapshot_lookup'), table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    op.add_column('dawah_requests', sa.Column('invited_religion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dawah_requests', 'religions', ['invited_religion_id'], ['religion_id'])
    op.add_column('interested_persons', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.add_column('interested_persons', sa.Column('religion', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'interested_persons', 'religions', ['religion_id'], ['religion_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interested_persons', type_='foreignkey')
    op.drop_column('interested_persons', 'religion')
    op.drop_column('interested_persons', 'religion_id')
    op.drop_constraint(None, 'dawah_requests', type_='foreignkey')
    op.drop_column('dawah_requests', 'invited_religion_id')
    op.create_table('dashboard_snapshots',
    sa.Column('snapshot_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('dashboard_snapshots_pkey')),
    sa.UniqueConstraint('entity_type', 'entity_id', name=op.f('uq_dashboard_snapshot_entity'))
    )
    op.create_index(op.f('idx_dashboard_snapshot_lookup'), 'dashboard_snapshots', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
