"""Add App Settings and OTP

Revision ID: fd60211f3a3d
Revises: ee8ec816b99d
Create Date: 2026-03-15 18:01:23.040987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd60211f3a3d'
down_revision = 'ee8ec816b99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('users', sa.Column('reset_otp', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
