"""Add app_language to users

Revision ID: 006_add_app_language_to_users
Revises: 005_add_admin_langs_and_faqs
Create Date: 2026-03-16 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006_add_app_language_to_users'
down_revision = '005_add_admin_langs_and_faqs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_language', sa.String(length=10), nullable=False, server_default='ar'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'app_language')
    # ### end Alembic commands ###
