"""add_dashboard_snapshots

Revision ID: 123456789abc
Revises: fd60211f3a3d
Create Date: 2026-03-22 16:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '123456789abc'
down_revision: Union[str, None] = 'ee8ec816b99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_snapshots',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_dashboard_snapshot_entity')
    )
    op.create_index('idx_dashboard_snapshot_lookup', 'dashboard_snapshots', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dashboard_snapshot_lookup', table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    # ### end Alembic commands ###
