"""add_ai_chat_conversations

Revision ID: 72f7d3463878
Revises: b6085835c7fd
Create Date: 2026-03-23 18:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f7d3463878'
down_revision: Union[str, None] = 'b6085835c7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='محادثة جديدة', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_conversations_user_id'), 'ai_chat_conversations', ['user_id'], unique=False)
    op.add_column('ai_chat_messages', sa.Column('conversation_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_ai_chat_messages_conversation_id'), 'ai_chat_messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'ai_chat_messages', 'ai_chat_conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_ai_chat_messages_conversation_id'), table_name='ai_chat_messages')
    op.drop_column('ai_chat_messages', 'conversation_id')
    op.drop_index(op.f('ix_ai_chat_conversations_user_id'), table_name='ai_chat_conversations')
    op.drop_table('ai_chat_conversations')
    # ### end Alembic commands ###
