"""add_session_id_to_ai_chat

Revision ID: b6085835c7fd
Revises: 008_seed_all_languages
Create Date: 2026-03-20 00:49:47.702100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6085835c7fd'
down_revision = '123456789abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    op.add_column('ai_chat_messages', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.alter_column('ai_chat_messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.alter_column('ai_chat_messages', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('ai_chat_messages', 'session_id')
    op.create_table('faqs',
    sa.Column('faq_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('faq_id', name=op.f('faqs_pkey'))
    )
    # ### end Alembic commands ###
