"""Add lead tracking and reporting

Revision ID: ee8ec816b99c
Revises: c0a1b2c3d4e5
Create Date: 2026-03-14 16:17:52.911750
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ee8ec816b99c'
down_revision = 'c0a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # Helper to check if type exists
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'communication_channel'")).fetchone()
    if not res:
        sa.Enum('phone', 'whatsapp', 'messenger', 'telegram', 'email', 'in_person', 'other', name='communication_channel').create(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_attempts',
    sa.Column('attempt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('preacher_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', postgresql.ENUM('phone', 'whatsapp', 'messenger', 'telegram', 'email', 'in_person', 'other', name='communication_channel', create_type=False), nullable=False),
    sa.Column('clicked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preacher_id'], ['preachers.preacher_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['dawah_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('dawah_reports',
    sa.Column('report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('preacher_id', sa.BigInteger(), nullable=False),
    sa.Column('communication_type', sa.String(length=100), nullable=True),
    sa.Column('communication_details', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preacher_id'], ['preachers.preacher_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['dawah_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.alter_column('messages', 'request_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index('idx_messages_receiver', 'messages', ['receiver_id'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_receiver', table_name='messages')
    op.alter_column('messages', 'request_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('dawah_reports')
    op.drop_table('contact_attempts')
    # ### end Alembic commands ###
